// components/MedicalReport.js
import React from "react";
import { Document, Page, Text, StyleSheet, View } from "@react-pdf/renderer";

// Define styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: "Helvetica",
    fontSize: 12,
    lineHeight: 1.6,
    color: "#333",
  },
  header: {
    textAlign: "center",
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#666",
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    borderBottom: "1px solid #0073e6",
    color: "#0073e6",
    marginBottom: 8,
    paddingBottom: 4,
  },
  field: {
    marginBottom: 6,
  },
  fieldLabel: {
    fontWeight: "bold",
  },
  footer: {
    marginTop: 20,
    textAlign: "center",
    fontSize: 10,
    color: "#777",
  },
});

type Props = {
  patient: {
    name: string;
    jmbg: string;
    email: string;
  };
  doctor: {
    name: string;
    specialization: string;
    email: string;
  };
  diagnosis: string;
  prescription: string;
};

// Create the Medical Report document
const MedicalReport = ({ patient, doctor, diagnosis, prescription }: Props) => (
  <Document>
    <Page style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Medical Report</Text>
        <Text style={styles.headerSubtitle}>Confidential Document</Text>
      </View>

      {/* Patient Details */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Patient Information</Text>
        <View style={styles.field}>
          <Text style={styles.fieldLabel}>Name:</Text>{" "}
          <Text>{patient.name}</Text>
        </View>
        <View style={styles.field}>
          <Text style={styles.fieldLabel}>ID:</Text> <Text>{patient.jmbg}</Text>
        </View>
        <View style={styles.field}>
          <Text style={styles.fieldLabel}>Email:</Text>{" "}
          <Text>{patient.email}</Text>
        </View>
      </View>

      {/* Doctor Information */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Doctor Information</Text>
        <View style={styles.field}>
          <Text style={styles.fieldLabel}>Name:</Text>{" "}
          <Text>{doctor.name}</Text>
        </View>
        <View style={styles.field}>
          <Text style={styles.fieldLabel}>Specialization:</Text>{" "}
          <Text>{doctor.specialization}</Text>
        </View>
        <View style={styles.field}>
          <Text style={styles.fieldLabel}>Email:</Text>{" "}
          <Text>{doctor.email}</Text>
        </View>
      </View>

      {/* Diagnosis */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Diagnosis</Text>
        <Text>{diagnosis}</Text>
      </View>

      {/* Prescription */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Prescription</Text>
        <Text>{prescription}</Text>
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text>
          This document is generated by TeleMed. For more information, visit{" "}
          <Text style={{ color: "#0073e6" }}>https://telemed.com</Text>.
        </Text>
      </View>
    </Page>
  </Document>
);

export default MedicalReport;
