export const AreaEnum = {
  UNSKO_SANSKI: "UNSKO_SANSKI",
  POSAVSKI: "POSAVSKI",
  TUZLANSKI: "TUZLANSKI",
  ZENICKO_DOBOJSKI: "ZENICKO_DOBOJSKI",
  BOSANSKO_PODRINJSKI: "BOSANSKO_PODRINJSKI",
  SREDNJOBOSANSKI: "SREDNJOBOSANSKI",
  HERCEGOVACKO_NERETVANSKI: "HERCEGOVACKO_NERETVANSKI",
  ZAPADNOHERCEGOVACKI: "ZAPADNOHERCEGOVACKI",
  SARAJEVO: "SARAJEVO",
  CANTON_10: "CANTON_10",
};
